version: '3'

services:
  bot:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: tg-autosender
    volumes:
      - .:/app:rw
    environment:
      - PYTHONUNBUFFERED=False
    restart: unless-stopped
  